"""Confirm=True sweep — PMG PBS remote config + node-side PBS backup jobs wrapper welds
(src/proximo/pmg.py + src/proximo/tools/pmg_mail.py, Wave 9f, full-surface campaign) + THE SECRET
CONTRACT proof for `password` AND `encryption-key`.

Mirrors the `_wire()`/`_Pmg` idiom already established in
`tests/test_confirm_sweep_pmg_ldap_fetchmail.py` (itself mirroring
`tests/test_confirm_sweep_pbs_node.py`'s own `_Pbs` template): `_svc` is monkeypatched (the ONE
shared audit ledger lives behind it — `_ledger()` reads `_svc()[3]`) and `_pmg` is monkeypatched
to a fake PmgBackend. This file duplicates its own `_Pmg`/`_wire` rather than importing another
confirm-sweep module's — same self-contained convention every confirm-sweep module in this repo
follows. New file (no prior confirm-sweep coverage existed for these 15 methods) per the Wave 9f
dispatch brief.

Each homogeneous confirm=True call proves the three welds every confirm-sweep module proves:
  1. return shape — status is the EXECUTED shape ("ok"/"submitted"), never "plan";
  2. the fake PmgBackend captured the underlying call (verb + path + EXACT payload, full dict
     equality — no subset matching);
  3. the ledger recorded a confirmed mutation — structural asserts only, never exact prose.

THE HEADLINE WELD (this chunk carries TWO CONFIRMED-echoing secrets, the 9c precedent extended to
a pair): `password` and `encryption-key` must NEVER appear raw in the on-disk ledger — read RAW
BYTES, not parsed JSON — on EITHER the dry-run plan path or the confirm path, while the real PMG
call (the fake's captured payload) DOES carry the raw values, because the mutation must actually
work. `pmg_pbs_remote_list`/`pmg_pbs_remote_get`/`pmg_node_pbs_jobs_list` are proven to strip BOTH
secrets at the read layer (mandatory on both list forms — CONFIRMED echoing on the live schema;
defensive on the single-item read — schema is bare there). A THIRD case unique to this chunk: the
create/update mutation's own RESPONSE may carry a server-generated `encryption-key` (when the
caller passes `encryption_key='autogen'`) — that value must reach the CALLER (there is no second
copy) but must NEVER reach the ledger. `fingerprint`/`master-pubkey` are the mirror-image proof —
PUBLIC, so they DO appear raw in the ledger, unredacted, on purpose. Sentinel values are
low-entropy (all-lowercase, hyphenated) per this repo's fixture-sentinel discipline (CLAUDE.md: a
mixed-case sentinel already failed the public gitleaks CI scan on v0.13.0).
"""

from __future__ import annotations

import json
from types import SimpleNamespace

import pytest

import proximo.server as server
from proximo.audit import AuditLedger
from proximo.backends import ProximoError
from proximo.config import ProximoConfig

_PASSWORD_SENTINEL = "sentinel-pbs-remote-password-value"  # noqa: S105 (test sentinel, not a real credential)
_ENCKEY_SENTINEL = "sentinel-pbs-remote-encryption-key-value"  # noqa: S105 (test sentinel)
_AUTOGEN_RETURN_SENTINEL = "sentinel-autogenerated-encryption-key"  # noqa: S105 (test sentinel)
_FINGERPRINT = ":".join(["ab"] * 32)

_SNAPSHOT_CREATE_STRING = "TASK:localhost:snapshot-create-not-a-real-upid"
_SNAPSHOT_RESTORE_STRING = "TASK:localhost:snapshot-restore-not-a-real-upid"
_VERIFY_UPID_STRING = "UPID:localhost:00000000:00000000:00000000:verify:r1:root@pam:"

_BACKUP_ID = "myhost"
_BACKUP_TIME = "2026-07-17T00:00:00Z"


class _Pmg:
    """Path-aware fake PmgBackend: records every _get/_post/_put/_delete call.

    `_get` returns a fixed, secret-FREE PBS remote config dict for `/config/pbs/r1` (the CAPTURE
    read `plan_pbs_remote_update`/`plan_pbs_remote_delete` use) and a fixed timer dict for
    `/nodes/pmg/pbs/r1/timer` (the CAPTURE read `plan_node_pbs_timer_create`/`_delete` use) —
    every other path gets `[]`/`{}` (list/dict reads default empty). `_post` returns the
    schema-confirmed ambiguous strings for snapshot create/restore/verify, and a fixed
    create-response dict for `/config/pbs`; `_put` returns a fixed update-response dict for
    `/config/pbs/r1`; `_delete` returns `None` throughout (every DELETE on this chunk's live
    schema returns `null`).
    """

    def __init__(self, remote_get_return=None, timer_get_return=None,
                 remote_create_return=None, remote_update_return=None):
        self._remote_get_return = remote_get_return or {
            "remote": "r1", "server": "pbs.example.com", "datastore": "ds1",
        }
        self._timer_get_return = timer_get_return if timer_get_return is not None else {}
        self._remote_create_return = remote_create_return or {"remote": "r1"}
        self._remote_update_return = remote_update_return or {"remote": "r1"}
        self.gets: list[tuple[str, dict | None]] = []
        self.posts: list[tuple[str, dict | None]] = []
        self.puts: list[tuple[str, dict | None]] = []
        self.deletes: list[tuple[str, dict | None]] = []

    def _get(self, path, params=None):
        self.gets.append((path, params))
        if path == "/config/pbs/r1":
            return self._remote_get_return
        if path == "/nodes/pmg/pbs/r1/timer":
            return self._timer_get_return
        return []

    def _post(self, path, data=None):
        self.posts.append((path, data))
        if path == "/config/pbs":
            return self._remote_create_return
        if path == "/nodes/pmg/pbs/r1/snapshot":
            return _SNAPSHOT_CREATE_STRING
        if path == f"/nodes/pmg/pbs/r1/snapshot/{_BACKUP_ID}/{_BACKUP_TIME}":
            return _SNAPSHOT_RESTORE_STRING
        if path == f"/nodes/pmg/pbs/r1/snapshot/{_BACKUP_ID}/{_BACKUP_TIME}/verify":
            return _VERIFY_UPID_STRING
        return None

    def _put(self, path, data=None):
        self.puts.append((path, data))
        if path == "/config/pbs/r1":
            return self._remote_update_return
        return None

    def _delete(self, path, params=None):
        self.deletes.append((path, params))
        return None


class _Api:
    """Minimal PVE API stub — only needed so server._svc() resolves (the ONE shared ledger lives
    behind it); pmg.py's/tools/pmg_mail.py's tools never touch this backend."""

    def __init__(self):
        self.config = SimpleNamespace(node="pve")


def _wire(tmp_path, monkeypatch, **pmg_kwargs):
    log = str(tmp_path / "audit.log")
    cfg = ProximoConfig(
        api_base_url="https://x:8006/api2/json", node="pve", token_path="/run/x",
        audit_log_path=log,
    )
    api = _Api()
    pmg = _Pmg(**pmg_kwargs)
    exec_ = SimpleNamespace()
    ledger = AuditLedger(log)
    monkeypatch.setattr(server, "_svc", lambda: (cfg, api, exec_, ledger))
    monkeypatch.setattr(server, "_pmg", lambda: (SimpleNamespace(node="pmg"), pmg))
    return cfg, pmg, ledger, log


def _entries(log: str) -> list[dict]:
    with open(log, encoding="utf-8") as f:
        return [json.loads(line) for line in f if line.strip()]


def _confirmed_entry(log: str, action: str, outcome: str) -> dict:
    entries = [e for e in _entries(log) if e["action"] == action and e["outcome"] == outcome]
    assert len(entries) == 1, f"expected exactly one {action!r}/{outcome!r} ledger entry, got {entries}"
    return entries[0]


# ---------------------------------------------------------------------------
# Homogeneous sweep — table-driven: "confirm=True reaches the right verb/path/data on the
# PmgBackend and records a confirmed mutation".
# ---------------------------------------------------------------------------

_SWEEP_CASES = [
    pytest.param(
        "pmg_pbs_remote_create",
        dict(remote="r1", datastore="ds1", server="pbs.example.com"),
        "ok", "posts", "/config/pbs",
        {"remote": "r1", "datastore": "ds1", "server": "pbs.example.com"},
        id="remote_create",
    ),
    pytest.param(
        "pmg_pbs_remote_update",
        dict(remote="r1", server="pbs2.example.com"),
        "ok", "puts", "/config/pbs/r1",
        {"server": "pbs2.example.com"},
        id="remote_update",
    ),
    pytest.param(
        "pmg_pbs_remote_delete",
        dict(remote="r1"),
        "ok", "deletes", "/config/pbs/r1",
        None,
        id="remote_delete",
    ),
    pytest.param(
        "pmg_node_pbs_snapshot_create",
        dict(remote="r1"),
        "submitted", "posts", "/nodes/pmg/pbs/r1/snapshot",
        {},
        id="snapshot_create",
    ),
    pytest.param(
        "pmg_node_pbs_snapshot_forget",
        dict(remote="r1", backup_id=_BACKUP_ID, backup_time=_BACKUP_TIME),
        "ok", "deletes", f"/nodes/pmg/pbs/r1/snapshot/{_BACKUP_ID}/{_BACKUP_TIME}",
        None,
        id="snapshot_forget",
    ),
    pytest.param(
        "pmg_node_pbs_snapshot_restore",
        dict(remote="r1", backup_id=_BACKUP_ID, backup_time=_BACKUP_TIME),
        "submitted", "posts", f"/nodes/pmg/pbs/r1/snapshot/{_BACKUP_ID}/{_BACKUP_TIME}",
        {"config": False, "database": True, "statistic": False},
        id="snapshot_restore",
    ),
    pytest.param(
        "pmg_node_pbs_snapshot_verify",
        dict(remote="r1", backup_id=_BACKUP_ID, backup_time=_BACKUP_TIME),
        "submitted", "posts", f"/nodes/pmg/pbs/r1/snapshot/{_BACKUP_ID}/{_BACKUP_TIME}/verify",
        {},
        id="snapshot_verify",
    ),
    pytest.param(
        "pmg_node_pbs_timer_create",
        dict(remote="r1"),
        "ok", "posts", "/nodes/pmg/pbs/r1/timer",
        {},
        id="timer_create",
    ),
    pytest.param(
        "pmg_node_pbs_timer_delete",
        dict(remote="r1"),
        "ok", "deletes", "/nodes/pmg/pbs/r1/timer",
        None,
        id="timer_delete",
    ),
]


@pytest.mark.parametrize(
    "tool_name,kwargs,expected_status,capture,path,data_exact", _SWEEP_CASES,
)
def test_confirm_true_executes_forwards_and_records(
    tmp_path, monkeypatch, tool_name, kwargs, expected_status, capture, path, data_exact,
):
    """confirm=True executes (never 'plan'), the fake captured the forwarded call, and the ledger
    recorded a confirmed mutation — the three welds every confirm-sweep module proves."""
    _, pmg, _, log = _wire(tmp_path, monkeypatch)
    fn = getattr(server, tool_name)

    out = fn(confirm=True, **kwargs)

    # weld 1: return shape.
    assert out["status"] == expected_status
    assert out["status"] != "plan"

    # weld 2: the fake captured the underlying call at the expected verb + path.
    calls = getattr(pmg, capture)
    assert calls, f"{tool_name} confirm=True never reached pmg.{capture}"
    call_path, call_data = calls[-1]
    assert call_path == path
    if data_exact is not None:
        assert call_data == data_exact

    # weld 3: ledger structural asserts — never exact prose.
    entry = _confirmed_entry(log, tool_name, expected_status)
    assert entry["mutation"] is True
    assert entry["detail"]["confirmed"] is True


# ---------------------------------------------------------------------------
# Ambiguous-string returns (fact: run_backup/restore are schema-ambiguous; verify is a
# schema-CONFIRMED UPID) — raw_result recorded in BOTH the response and the ledger detail for the
# two truly ambiguous ones.
# ---------------------------------------------------------------------------

def test_snapshot_create_records_raw_result_both_places(tmp_path, monkeypatch):
    _, _, _, log = _wire(tmp_path, monkeypatch)
    out = server.pmg_node_pbs_snapshot_create(remote="r1", confirm=True)
    assert out["result"] == _SNAPSHOT_CREATE_STRING
    entry = _confirmed_entry(log, "pmg_node_pbs_snapshot_create", "submitted")
    assert entry["detail"]["raw_result"] == _SNAPSHOT_CREATE_STRING


def test_snapshot_restore_records_raw_result_both_places(tmp_path, monkeypatch):
    _, _, _, log = _wire(tmp_path, monkeypatch)
    out = server.pmg_node_pbs_snapshot_restore(
        remote="r1", backup_id=_BACKUP_ID, backup_time=_BACKUP_TIME, confirm=True,
    )
    assert out["result"] == _SNAPSHOT_RESTORE_STRING
    entry = _confirmed_entry(log, "pmg_node_pbs_snapshot_restore", "submitted")
    assert entry["detail"]["raw_result"] == _SNAPSHOT_RESTORE_STRING


def test_snapshot_verify_returns_the_upid(tmp_path, monkeypatch):
    _, _, _, _ = _wire(tmp_path, monkeypatch)
    out = server.pmg_node_pbs_snapshot_verify(
        remote="r1", backup_id=_BACKUP_ID, backup_time=_BACKUP_TIME, confirm=True,
    )
    assert out["result"] == _VERIFY_UPID_STRING
    assert out["status"] == "submitted"


# ---------------------------------------------------------------------------
# Dry-run (confirm=False) — proves the PLAN path never touches the PmgBackend's write verbs, and
# that update/delete/timer plans CAPTURE current config via a live read.
# ---------------------------------------------------------------------------

def test_remote_create_dry_run_never_posts(tmp_path, monkeypatch):
    _, pmg, _, _ = _wire(tmp_path, monkeypatch)
    out = server.pmg_pbs_remote_create(remote="r1", datastore="ds1", server="pbs.example.com", confirm=False)
    assert out["status"] == "plan"
    assert not pmg.posts


def test_remote_update_dry_run_reads_but_never_puts(tmp_path, monkeypatch):
    _, pmg, _, _ = _wire(tmp_path, monkeypatch)
    out = server.pmg_pbs_remote_update(remote="r1", server="pbs2.example.com", confirm=False)
    assert out["status"] == "plan"
    assert out["current"]["server"] == "pbs.example.com"
    assert not pmg.puts


def test_remote_update_dry_run_requires_at_least_one_field(tmp_path, monkeypatch):
    _wire(tmp_path, monkeypatch)
    with pytest.raises(ProximoError):
        server.pmg_pbs_remote_update(remote="r1", confirm=False)


def test_remote_delete_dry_run_reads_but_never_deletes(tmp_path, monkeypatch):
    _, pmg, _, _ = _wire(tmp_path, monkeypatch)
    out = server.pmg_pbs_remote_delete(remote="r1", confirm=False)
    assert out["status"] == "plan"
    assert out["current"]["server"] == "pbs.example.com"
    assert not pmg.deletes


def test_snapshot_forget_dry_run_never_deletes(tmp_path, monkeypatch):
    _, pmg, _, _ = _wire(tmp_path, monkeypatch)
    out = server.pmg_node_pbs_snapshot_forget(
        remote="r1", backup_id=_BACKUP_ID, backup_time=_BACKUP_TIME, confirm=False,
    )
    assert out["status"] == "plan"
    assert not pmg.deletes


def test_snapshot_restore_dry_run_never_posts(tmp_path, monkeypatch):
    _, pmg, _, _ = _wire(tmp_path, monkeypatch)
    out = server.pmg_node_pbs_snapshot_restore(
        remote="r1", backup_id=_BACKUP_ID, backup_time=_BACKUP_TIME, confirm=False,
    )
    assert out["status"] == "plan"
    assert "no undo" in out["blast_radius"][0].lower()
    assert not pmg.posts


def test_timer_create_dry_run_never_posts(tmp_path, monkeypatch):
    _, pmg, _, _ = _wire(tmp_path, monkeypatch)
    out = server.pmg_node_pbs_timer_create(remote="r1", confirm=False)
    assert out["status"] == "plan"
    assert not pmg.posts


def test_timer_delete_dry_run_reads_but_never_deletes(tmp_path, monkeypatch):
    _, pmg, _, _ = _wire(tmp_path, monkeypatch, timer_get_return={"schedule": "daily"})
    out = server.pmg_node_pbs_timer_delete(remote="r1", confirm=False)
    assert out["status"] == "plan"
    assert out["current"]["schedule"] == "daily"
    assert not pmg.deletes


# ---------------------------------------------------------------------------
# Reads — confirm the wrapper reaches the PmgBackend with the right path (no confirm= gate).
# ---------------------------------------------------------------------------

def test_remote_list_read_reaches_pmg(tmp_path, monkeypatch):
    _, pmg, _, _ = _wire(tmp_path, monkeypatch)
    server.pmg_pbs_remote_list()
    call_path, _ = pmg.gets[-1]
    assert call_path == "/config/pbs"


def test_remote_get_read_reaches_pmg(tmp_path, monkeypatch):
    _, pmg, _, _ = _wire(tmp_path, monkeypatch)
    server.pmg_pbs_remote_get(remote="r1")
    call_path, _ = pmg.gets[-1]
    assert call_path == "/config/pbs/r1"


def test_node_pbs_jobs_list_read_reaches_pmg(tmp_path, monkeypatch):
    _, pmg, _, _ = _wire(tmp_path, monkeypatch)
    server.pmg_node_pbs_jobs_list()
    call_path, _ = pmg.gets[-1]
    assert call_path == "/nodes/pmg/pbs"


def test_snapshots_list_read_reaches_pmg(tmp_path, monkeypatch):
    _, pmg, _, _ = _wire(tmp_path, monkeypatch)
    server.pmg_node_pbs_snapshots_list(remote="r1")
    call_path, _ = pmg.gets[-1]
    assert call_path == "/nodes/pmg/pbs/r1/snapshot"


def test_snapshot_get_read_reaches_pmg(tmp_path, monkeypatch):
    _, pmg, _, _ = _wire(tmp_path, monkeypatch)
    server.pmg_node_pbs_snapshot_get(remote="r1", backup_id=_BACKUP_ID)
    call_path, _ = pmg.gets[-1]
    assert call_path == f"/nodes/pmg/pbs/r1/snapshot/{_BACKUP_ID}"


def test_timer_get_read_reaches_pmg(tmp_path, monkeypatch):
    _, pmg, _, _ = _wire(tmp_path, monkeypatch)
    server.pmg_node_pbs_timer_get(remote="r1")
    call_path, _ = pmg.gets[-1]
    assert call_path == "/nodes/pmg/pbs/r1/timer"


# ---------------------------------------------------------------------------
# THE HEADLINE WELD — secret-never-in-ledger for `password` AND `encryption-key` (both fields, one
# call each), plus the read-layer strip proofs (mandatory on both list forms, defensive on the
# single-item read), plus the unique "secret in a mutation's own RETURN" proof for the
# encryption_key='autogen' response shape. Sentinel values are low-entropy/all-lowercase/hyphenated
# per this repo's fixture-sentinel discipline.
# ---------------------------------------------------------------------------

def test_remote_create_confirm_never_writes_secrets_to_ledger(tmp_path, monkeypatch):
    """weld 1: the operator's real PBS call DOES carry the raw password AND encryption-key (the
    mutation must actually work) — the fake captured both. weld 2: read the ledger file RAW
    (bytes, not parsed JSON) and assert NEITHER secret substring appears anywhere in the file."""
    _, pmg, _, log = _wire(tmp_path, monkeypatch)

    out = server.pmg_pbs_remote_create(
        remote="r1", datastore="ds1", server="pbs.example.com",
        password=_PASSWORD_SENTINEL, encryption_key=_ENCKEY_SENTINEL, confirm=True,
    )

    assert out["status"] == "ok"
    assert out["status"] != "plan"

    # weld 1: the fake captured the underlying POST with BOTH raw secrets.
    assert pmg.posts, "pmg_pbs_remote_create confirm=True never reached pmg._post"
    call_path, call_data = pmg.posts[-1]
    assert call_path == "/config/pbs"
    assert call_data["password"] == _PASSWORD_SENTINEL
    assert call_data["encryption-key"] == _ENCKEY_SENTINEL

    # weld 2: ledger entries (parsed JSON) never carry either secret sentinel.
    entries = _entries(log)
    assert entries, "no ledger entries recorded at all"
    assert all(_PASSWORD_SENTINEL not in json.dumps(e) for e in entries)
    assert all(_ENCKEY_SENTINEL not in json.dumps(e) for e in entries)
    entry = _confirmed_entry(log, "pmg_pbs_remote_create", "ok")
    assert "password" not in entry["detail"]
    assert "encryption-key" not in entry["detail"]

    # THE HEADLINE WELD: read the ledger file RAW (bytes) — neither secret appears NOWHERE.
    raw = open(log, "rb").read()
    assert _PASSWORD_SENTINEL.encode("utf-8") not in raw
    assert _ENCKEY_SENTINEL.encode("utf-8") not in raw

    # MIRROR-IMAGE: server/datastore ARE present raw in the on-disk ledger (non-secret,
    # deliberately visible).
    assert b"pbs.example.com" in raw
    assert b"ds1" in raw


def test_remote_create_confirm_forwards_namespace(tmp_path, monkeypatch):
    """Major-1 fix: `namespace` (real, schema-confirmed, optional on POST /config/pbs) must
    reach the wire payload — it was previously silently unreachable via this wrapper."""
    _, pmg, _, _ = _wire(tmp_path, monkeypatch)
    out = server.pmg_pbs_remote_create(
        remote="r1", datastore="ds1", server="pbs.example.com",
        namespace="tenant-a", confirm=True,
    )
    assert out["status"] == "ok"
    call_path, call_data = pmg.posts[-1]
    assert call_path == "/config/pbs"
    assert call_data["namespace"] == "tenant-a"


def test_remote_update_confirm_forwards_namespace(tmp_path, monkeypatch):
    """Major-1 fix: `namespace` on PUT /config/pbs/{remote}, same wiring gap."""
    _, pmg, _, _ = _wire(tmp_path, monkeypatch)
    out = server.pmg_pbs_remote_update(remote="r1", namespace="tenant-a", confirm=True)
    assert out["status"] == "ok"
    call_path, call_data = pmg.puts[-1]
    assert call_path == "/config/pbs/r1"
    assert call_data["namespace"] == "tenant-a"


def test_remote_create_dry_run_plan_never_carries_secrets(tmp_path, monkeypatch):
    """Even confirm=False (the returned PLAN dict itself, not just the ledger) must never carry
    either raw secret — the plan is returned directly to the calling agent."""
    _wire(tmp_path, monkeypatch)

    out = server.pmg_pbs_remote_create(
        remote="r1", datastore="ds1", server="pbs.example.com",
        password=_PASSWORD_SENTINEL, encryption_key=_ENCKEY_SENTINEL, confirm=False,
    )

    assert out["status"] == "plan"
    dumped = json.dumps(out)
    assert _PASSWORD_SENTINEL not in dumped
    assert _ENCKEY_SENTINEL not in dumped
    assert "pbs.example.com" in dumped  # server IS visible — not secret


def test_remote_update_confirm_never_writes_secrets_to_ledger(tmp_path, monkeypatch):
    _, pmg, _, log = _wire(tmp_path, monkeypatch)

    out = server.pmg_pbs_remote_update(
        remote="r1", password=_PASSWORD_SENTINEL, encryption_key=_ENCKEY_SENTINEL, confirm=True,
    )

    assert out["status"] == "ok"
    assert pmg.puts
    _, call_data = pmg.puts[-1]
    assert call_data["password"] == _PASSWORD_SENTINEL
    assert call_data["encryption-key"] == _ENCKEY_SENTINEL

    raw = open(log, "rb").read()
    assert _PASSWORD_SENTINEL.encode("utf-8") not in raw
    assert _ENCKEY_SENTINEL.encode("utf-8") not in raw


def test_remote_update_dry_run_plan_never_carries_secrets(tmp_path, monkeypatch):
    _wire(tmp_path, monkeypatch)

    out = server.pmg_pbs_remote_update(
        remote="r1", password=_PASSWORD_SENTINEL, encryption_key=_ENCKEY_SENTINEL, confirm=False,
    )

    assert out["status"] == "plan"
    dumped = json.dumps(out)
    assert _PASSWORD_SENTINEL not in dumped
    assert _ENCKEY_SENTINEL not in dumped


def test_remote_update_capture_secrets_never_reach_ledger(tmp_path, monkeypatch):
    """Defense-in-depth: the CAPTURE read (pbs_remote_get already strips both secrets at the read
    layer, but wire the fake to return them anyway to prove the redaction-on-top-of-strip holds
    even if the read-layer strip regressed) must never leak into the ledger either, on BOTH
    confirm=False and confirm=True paths."""
    leaked_pw = "sentinel-leaked-from-a-pbs-remote-get-password"  # noqa: S105
    leaked_key = "sentinel-leaked-from-a-pbs-remote-get-enckey"  # noqa: S105
    _, _, _, log = _wire(
        tmp_path, monkeypatch,
        remote_get_return={"remote": "r1", "password": leaked_pw, "encryption-key": leaked_key},
    )

    out = server.pmg_pbs_remote_update(remote="r1", server="pbs2.example.com", confirm=False)
    assert out["status"] == "plan"
    assert leaked_pw not in json.dumps(out)
    assert leaked_key not in json.dumps(out)

    out = server.pmg_pbs_remote_update(remote="r1", server="pbs2.example.com", confirm=True)
    assert out["status"] == "ok"

    raw = open(log, "rb").read()
    assert leaked_pw.encode("utf-8") not in raw
    assert leaked_key.encode("utf-8") not in raw


def test_remote_delete_capture_secrets_never_reach_ledger(tmp_path, monkeypatch):
    leaked_pw = "sentinel-leaked-from-pbs-remote-delete-capture-pw"  # noqa: S105
    leaked_key = "sentinel-leaked-from-pbs-remote-delete-capture-key"  # noqa: S105
    _, _, _, log = _wire(
        tmp_path, monkeypatch,
        remote_get_return={"remote": "r1", "password": leaked_pw, "encryption-key": leaked_key},
    )

    out = server.pmg_pbs_remote_delete(remote="r1", confirm=True)

    assert out["status"] == "ok"
    raw = open(log, "rb").read()
    assert leaked_pw.encode("utf-8") not in raw
    assert leaked_key.encode("utf-8") not in raw


def test_remote_list_strips_secrets_at_read_layer_mandatory(tmp_path, monkeypatch):
    """MANDATORY (not defensive) — the live schema CONFIRMS both password and encryption-key echo
    on the list endpoint."""
    leaked_pw = "sentinel-leaked-pw-from-remote-list"  # noqa: S105
    leaked_key = "sentinel-leaked-key-from-remote-list"  # noqa: S105

    class _LeakyPmg(_Pmg):
        def _get(self, path, params=None):
            self.gets.append((path, params))
            if path == "/config/pbs":
                return [{"remote": "r1", "server": "pbs.example.com",
                          "password": leaked_pw, "encryption-key": leaked_key,
                          "fingerprint": _FINGERPRINT}]
            return super()._get(path, params)

    log = str(tmp_path / "audit.log")
    cfg = ProximoConfig(api_base_url="https://x:8006/api2/json", node="pve", token_path="/run/x",
                         audit_log_path=log)
    pmg = _LeakyPmg()
    ledger = AuditLedger(log)
    monkeypatch.setattr(server, "_svc", lambda: (cfg, _Api(), SimpleNamespace(), ledger))
    monkeypatch.setattr(server, "_pmg", lambda: (SimpleNamespace(node="pmg"), pmg))

    result = server.pmg_pbs_remote_list()
    dumped = json.dumps(result)
    assert leaked_pw not in dumped
    assert leaked_key not in dumped
    assert result[0]["remote"] == "r1"
    # fingerprint is PUBLIC — passes through unredacted.
    assert result[0]["fingerprint"] == _FINGERPRINT


def test_remote_get_strips_secrets_at_read_layer_defensive(tmp_path, monkeypatch):
    """DEFENSIVE (schema is bare, `returns: {}` — genuinely unconfirmed either way) — applied
    regardless, using the SAME mechanism as the mandatory list strip."""
    leaked_pw = "sentinel-leaked-pw-from-remote-get"  # noqa: S105
    leaked_key = "sentinel-leaked-key-from-remote-get"  # noqa: S105
    _, _, _, _ = _wire(
        tmp_path, monkeypatch,
        remote_get_return={"remote": "r1", "password": leaked_pw, "encryption-key": leaked_key},
    )

    result = server.pmg_pbs_remote_get(remote="r1")
    dumped = json.dumps(result)
    assert leaked_pw not in dumped
    assert leaked_key not in dumped
    assert result["remote"] == "r1"


def test_node_pbs_jobs_list_strips_secrets_at_read_layer_mandatory(tmp_path, monkeypatch):
    """MANDATORY — literally the same item schema as the global /config/pbs list, CONFIRMED
    echoing both secrets."""
    leaked_pw = "sentinel-leaked-pw-from-node-jobs-list"  # noqa: S105
    leaked_key = "sentinel-leaked-key-from-node-jobs-list"  # noqa: S105

    class _LeakyPmg(_Pmg):
        def _get(self, path, params=None):
            self.gets.append((path, params))
            if path == "/nodes/pmg/pbs":
                return [{"remote": "r1", "password": leaked_pw, "encryption-key": leaked_key}]
            return super()._get(path, params)

    log = str(tmp_path / "audit.log")
    cfg = ProximoConfig(api_base_url="https://x:8006/api2/json", node="pve", token_path="/run/x",
                         audit_log_path=log)
    pmg = _LeakyPmg()
    ledger = AuditLedger(log)
    monkeypatch.setattr(server, "_svc", lambda: (cfg, _Api(), SimpleNamespace(), ledger))
    monkeypatch.setattr(server, "_pmg", lambda: (SimpleNamespace(node="pmg"), pmg))

    result = server.pmg_node_pbs_jobs_list()
    dumped = json.dumps(result)
    assert leaked_pw not in dumped
    assert leaked_key not in dumped
    assert result[0]["remote"] == "r1"


def test_fingerprint_and_master_pubkey_pass_through_unredacted_in_ledger(tmp_path, monkeypatch):
    """MIRROR-IMAGE proof: fingerprint/master-pubkey are PUBLIC — they DO appear raw in the
    on-disk ledger, on purpose (not a leak; the module docstring's own argued exception)."""
    _, pmg, _, log = _wire(tmp_path, monkeypatch)

    out = server.pmg_pbs_remote_create(
        remote="r1", datastore="ds1", server="pbs.example.com",
        fingerprint=_FINGERPRINT, master_pubkey="sentinel-pem-public-key-blob", confirm=True,
    )

    assert out["status"] == "ok"
    _, call_data = pmg.posts[-1]
    assert call_data["fingerprint"] == _FINGERPRINT
    assert call_data["master-pubkey"] == "sentinel-pem-public-key-blob"

    raw = open(log, "rb").read()
    assert _FINGERPRINT.encode("utf-8") in raw
    assert b"sentinel-pem-public-key-blob" in raw


def test_remote_create_autogen_response_reaches_caller_but_never_ledger(tmp_path, monkeypatch):
    """THE UNIQUE THIRD CASE: when encryption_key='autogen', PBS may return a server-generated
    encryption-key in the CREATE response itself (config.encryption-key). That value MUST reach
    the caller (there is no second copy) but MUST NEVER be recorded to the ledger — the
    TFA-recovery-code "secret in a mutation's own RETURN" precedent, applied proactively here."""
    _, _, _, log = _wire(
        tmp_path, monkeypatch,
        remote_create_return={"remote": "r1", "config": {"encryption-key": _AUTOGEN_RETURN_SENTINEL}},
    )

    out = server.pmg_pbs_remote_create(
        remote="r1", datastore="ds1", server="pbs.example.com",
        encryption_key="autogen", confirm=True,
    )

    assert out["status"] == "ok"
    # reaches the caller — there is no second copy of an auto-generated key.
    assert out["result"]["config"]["encryption-key"] == _AUTOGEN_RETURN_SENTINEL

    # never recorded to the ledger.
    raw = open(log, "rb").read()
    assert _AUTOGEN_RETURN_SENTINEL.encode("utf-8") not in raw
    entry = _confirmed_entry(log, "pmg_pbs_remote_create", "ok")
    assert "result" not in entry["detail"]
    assert "config" not in entry["detail"]


def test_remote_update_autogen_response_reaches_caller_but_never_ledger(tmp_path, monkeypatch):
    """Same proof as create, for update's response shape."""
    _, _, _, log = _wire(
        tmp_path, monkeypatch,
        remote_update_return={"remote": "r1", "config": {"encryption-key": _AUTOGEN_RETURN_SENTINEL}},
    )

    out = server.pmg_pbs_remote_update(remote="r1", encryption_key="autogen", confirm=True)

    assert out["status"] == "ok"
    assert out["result"]["config"]["encryption-key"] == _AUTOGEN_RETURN_SENTINEL

    raw = open(log, "rb").read()
    assert _AUTOGEN_RETURN_SENTINEL.encode("utf-8") not in raw
    entry = _confirmed_entry(log, "pmg_pbs_remote_update", "ok")
    assert "result" not in entry["detail"]
    assert "config" not in entry["detail"]


def test_pmg_node_pbs_snapshot_forget_detail_includes_remote(tmp_path, monkeypatch):
    """Mutation ledger detail includes the remote id for audit trail clarity."""
    _, _, _, log = _wire(tmp_path, monkeypatch)

    out = server.pmg_node_pbs_snapshot_forget(
        remote="r1", backup_id=_BACKUP_ID, backup_time=_BACKUP_TIME, confirm=True,
    )

    assert out["status"] == "ok"
    entry = _confirmed_entry(log, "pmg_node_pbs_snapshot_forget", "ok")
    assert entry["detail"]["remote"] == "r1"
